FROM python:3.12-slim-bookworm

WORKDIR /app

COPY pyproject.toml .
COPY app ./app

RUN pip install --no-cache-dir -e .

EXPOSE 8010

CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8010"]
